env:
  global:
    - secure: TbmzGz6+qykqlXVoSmObKgp06s8xHW1kj9msAmeISS+W030g0NYbuq553Rw4yYa3n0tDrAjXSVp0fEAX6tU03hiky6drssuZcHzF1HypEunnAUt7gJ0UQVViQGu3jaiXWtkyuXAF5Rj3PEONH43/lOj1fhlUe/Lnf0FbvEWLPec=
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
  directories:
    - $HOME/elfutils
script:
  - echo passed
before_cache:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_elfutils2.sh
  - . install_elfutils2.sh
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
