[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of a Least Recently Used caching algorithm in a container which may be limited by size or time, ordered by most recently seen."
documentation = "http://maidsafe.net/lru_time_cache/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "lru_time_cache"
readme = "README.md"
repository = "https://github.com/maidsafe/lru_time_cache"
version = "0.2.7"

[dependencies]
clippy = {version = "~0.0.44", optional = true}
time = "~0.1.34"

[dev-dependencies]
rand = "~0.3.14"
