[package]
name = "lru_time_cache"
version = "0.2.6"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of a Least Recently Used caching algorithm in a container which may be limited by size or time, ordered by most recently seen."
documentation = "http://maidsafe.net/lru_time_cache/latest"
repository = "https://github.com/maidsafe/lru_time_cache"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
time = "~0.1.34"

[dev-dependencies]
rand = "~0.3.12"
